// lib/purchases.ts — RevenueCat adapter.
//
// Per-module non-consumable unlocks. The RevenueCat native module is loaded
// through a guarded require, so in Expo Go (where it is absent) a mock grants
// locally and the paywall stays fully testable. The SAME code runs in mock and
// live; going live needs only the appl_ key, the product ids, and an EAS build.
//
// Ownership is read as the UNION of allPurchasedProductIdentifiers and
// nonSubscriptionTransactions[].productIdentifier, which survives SDK field
// changes.

import { Platform } from 'react-native';
import Constants from 'expo-constants';
import { useStore } from './store';
import { MODULES, productIdForModule } from './bank';
import type { Exam } from './types';

// TODO: replace with the appl_ key generated by the new RevenueCat app config.
export const REVENUECAT_IOS_API_KEY = 'appl_REPLACE_WITH_IOS_KEY';

// DEV-ONLY: when running in mock mode (Expo Go or no real key yet), unlock every
// module so the question banks are browsable without a live store. This NEVER
// runs in a real build with a valid key. Flip to false to preview the paywall
// flow in Expo Go (then tap a module's Unlock button to grant it via the mock).
const DEV_UNLOCK_ALL = true;

type PurchasesModule = any;

let Purchases: PurchasesModule | null = null;
let isLive = false;

// Expo Go bundles the react-native-purchases JS module, but the NATIVE store is
// unavailable, so configure() throws. Detect the runtime/key directly instead of
// relying on the require failing (it doesn't).
function inExpoGo(): boolean {
  try {
    return Constants.executionEnvironment === 'storeClient';
  } catch {
    return false;
  }
}

function keyIsPlaceholder(): boolean {
  return !REVENUECAT_IOS_API_KEY || REVENUECAT_IOS_API_KEY.includes('REPLACE');
}

export function isMockMode(): boolean {
  return inExpoGo() || keyIsPlaceholder();
}

function loadPurchases(): PurchasesModule | null {
  // Force mock mode in Expo Go or before a real key is set, even though the JS
  // module is requireable -- its native store would throw on configure/purchase.
  if (isMockMode()) {
    Purchases = null;
    isLive = false;
    return null;
  }
  if (Purchases !== null) return Purchases;
  try {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    Purchases = require('react-native-purchases').default;
    isLive = !!Purchases;
  } catch {
    Purchases = null;
    isLive = false;
  }
  return Purchases;
}

function grantAllModulesLocally(): void {
  const all = MODULES.map((m) => productIdForModule(m.id));
  useStore.getState().setUnlocked(all);
}

function ownedFromCustomerInfo(info: any): string[] {
  const a: string[] = info?.allPurchasedProductIdentifiers ?? [];
  const b: string[] = (info?.nonSubscriptionTransactions ?? [])
    .map((t: any) => t?.productIdentifier)
    .filter(Boolean);
  return Array.from(new Set([...a, ...b]));
}

export async function configure(): Promise<void> {
  const P = loadPurchases();
  if (!P) {
    // Mock mode (Expo Go or no real key). Don't touch the native store.
    // Optionally unlock everything so the banks are browsable while testing.
    if (DEV_UNLOCK_ALL) grantAllModulesLocally();
    return;
  }
  try {
    if (Platform.OS === 'ios') {
      P.configure({ apiKey: REVENUECAT_IOS_API_KEY });
    }
    P.addCustomerInfoUpdateListener((info: any) => {
      useStore.getState().setUnlocked(ownedFromCustomerInfo(info));
    });
    const info = await P.getCustomerInfo();
    useStore.getState().setUnlocked(ownedFromCustomerInfo(info));
  } catch {
    // fall back silently to whatever is persisted in the store
  }
}

export function isLiveMode(): boolean {
  loadPurchases();
  return isLive;
}

export function isModuleOwned(exam: Exam): boolean {
  return useStore.getState().unlocked.includes(productIdForModule(exam));
}

// Buy a module. In mock mode this grants locally so the paywall flow is testable.
export async function purchaseModule(exam: Exam): Promise<boolean> {
  const productId = productIdForModule(exam);
  const P = loadPurchases();
  if (!P) {
    useStore.getState().addUnlocked(productId);
    return true;
  }
  try {
    const products = await P.getProducts([productId]);
    if (!products || products.length === 0) return false;
    const { customerInfo } = await P.purchaseStoreProduct(products[0]);
    useStore.getState().setUnlocked(ownedFromCustomerInfo(customerInfo));
    return isModuleOwned(exam);
  } catch (e: any) {
    if (e?.userCancelled) return false;
    return false;
  }
}

export async function restorePurchases(): Promise<void> {
  const P = loadPurchases();
  if (!P) return;
  try {
    const info = await P.restorePurchases();
    useStore.getState().setUnlocked(ownedFromCustomerInfo(info));
  } catch {
    // ignore
  }
}

export function priceLabelFallback(): string {
  return '$19.99';
}

// Best-effort localized price for a module (falls back to the static label).
export async function priceForModule(exam: Exam): Promise<string> {
  const P = loadPurchases();
  if (!P) return priceLabelFallback();
  try {
    const products = await P.getProducts([productIdForModule(exam)]);
    return products?.[0]?.priceString ?? priceLabelFallback();
  } catch {
    return priceLabelFallback();
  }
}

export { MODULES };
